### ISSUE TITLE
Show a complete command line and its output in the readme

### ISSUE THREAD

**Issue by dtolnay** [BrandtM/cargo-example#2]
From skimming the readme I still can't figure out what I need to type to run a crate's example. The readme mentions `cargo example ...args` but I don't know how to say which crate or which example to run. The readme also mentions `cargo run example ...args` and `cargo --example`, neither of which are real commands.

I would expect to see a complete screenshot or console codeblock showing the entire intended usage on some popular crate like rand, as in:

```console
$ cargo example ??? ??? monte-carlo
    Compiling rand v0.7.0 (/git/rand)
    Finished dev [unoptimized + debuginfo] target(s) in 1.56s
    Running `target/debug/examples/monte-carlo`

  π is approximately 3.142296
```

**Comment by BrandtM** [comment]
You're right, this is quite confusing. Obviously I left the most important part out :D  
So when you're using the installed version the usage would be `cargo example <crate> <args>`.  
And when you're running it from source the usage is `cargo run example <crate> <args>`  

I hope that helps. I'll improve the documentation and provide visual aid later.
